### ISSUE TITLE
Ruby vs Python

### ISSUE THREAD

**Issue by shotgundebugging** [gov-ithub/cazier_auto#3]
Salut,

Ați trecut definitiv de la Ruby la Python? M-a atras proiectul pentru că era singurul scris în Ruby.

Mircea, voluntar GovITHub

**Comment by mess110** [comment]
Django is nice, dar petrec putin mai mult timp facand un feature decat as petrece facand proiectul in Rails. Au mai fost persoane care au zis ca prefera Rails.

Singurul proiect in Ruby? Hm.. Ruby represent!

Este posibil sa trecem pe Rails.

PS: we are living in the same town

**Comment by shotgundebugging** [comment]
Django is nice, desigur. Rails și ecosistemul Rails îmi sunt mai familiare, și pentru mine ar fi opțiunea cea mai comodă.

@mess110, ar fi fain să ne vedem, mai ales dacă alegem să lucrăm pe același proiect.
